/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-27 19:16:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Bloques_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Aplicacion UCOMaps-En construccion</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"estilo1.css\" media=\"screen\"/>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t<h1>Registrar nuevo bloque en UCOMAPS</h1>\r\n");
      out.write("<form action=\"BloquesControlador\" method=\"POST\"> \r\n");
      out.write("\t<p>Ingrese el nombre del bloque: <input type=\"text\" name=\"nombloque\" value=\"");
      out.print(request.getParameter("nombrebloque")!=null?request.getParameter("nombloque"):"");
      out.write("\"  />\r\n");
      out.write("\t<p>Ingrese el numero de pisos: <input type=\"text\" name=\"numpiso\" value=\"");
      out.print(request.getParameter("numpisos")!=null?request.getParameter("numpisos"):"");
      out.write("\"  />\r\n");
      out.write("\t<p>Ingrese el numero de aulas: <input type=\"text\" name=\"numaulas\" value=\"");
      out.print(request.getParameter("numaulas")!=null?request.getParameter("numaulas"):"");
      out.write("\"  />\r\n");
      out.write("\t<p>Ingrese el numero de laboratorios y/o salas: <input type=\"text\" name=\"numlabsalas\" value=\"");
      out.print(request.getParameter("numlabsalas")!=null?request.getParameter("numlabsalas"):"");
      out.write("\"  />\r\n");
      out.write("\t<p>Ingrese el numero de oficinas y facultades que tiene:<input type=\"text\" name=\"oficinasfacultades\" value=\"");
      out.print(request.getParameter("oficinasfacultades")!=null?request.getParameter("oficinasfacultades"):"");
      out.write("\"  />\r\n");
      out.write("\t<p>Ingrese el numero de baños:<input type=\"text\" name=\"numbanos\" value=\"");
      out.print(request.getParameter("numbanos")!=null?request.getParameter("numbanos"):"");
      out.write("\"  />\r\n");
      out.write("\t<p>Cuenta con oratorios:\r\n");
      out.write("\t\t\tSi:<input type=\"radio\" name=\"oratorios\" value=\"s\" value=\"");
      out.print(request.getParameter("oratorios")!=null && request.getParameter("oratorios").equals("n")?"selected='selected'":"");
      out.write("\" checked=\"checked\"/>\r\n");
      out.write("\t\t\tNo:<input type=\"radio\" name=\"oratorios\" value=\"n\" value=\"");
      out.print(request.getParameter("oratorios")!=null?request.getParameter("oratorios"):"");
      out.write("\" />\r\n");
      out.write("\t<p>Cuenta con zonas de parqueo:\r\n");
      out.write("\t\t\tSi:<input type=\"radio\" name=\"parqueo\" value=\"s\" value=\"");
      out.print(request.getParameter("parqueo")!=null && request.getParameter("parqueo").equals("n")?"selected='selected'":"");
      out.write("\" checked=\"checked\"/>\r\n");
      out.write("\t\t\tNo:<input type=\"radio\" name=\"parqueo\" value=\"n\" value=\"");
      out.print(request.getParameter("parqueo")!=null?request.getParameter("parqueo"):"");
      out.write("\" />\t\t\r\n");
      out.write("\t<p>Cuenta con zonas de estudio:\r\n");
      out.write("\t\t\tSi:<input type=\"radio\" name=\"estudio\" value=\"s\" value=\"");
      out.print(request.getParameter("estudio")!=null && request.getParameter("estudio").equals("n")?"selected='selected'":"");
      out.write("\" checked=\"checked\"/>\r\n");
      out.write("\t\t\tNo:<input type=\"radio\" name=\"estudio\" value=\"n\" value=\"");
      out.print(request.getParameter("estudio")!=null?request.getParameter("estudio"):"");
      out.write("\" />\r\n");
      out.write("\t <p><input type=\"submit\" name=\"ingresar\" value=\"Ingresar Bloque\" />\r\n");
      out.write("</form>\r\n");
      out.write("<a href=\"MenuPrincipal.html\">Regrese al Menu Principal</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
